pipeline
{
agent {
  label 'dev'
}

parameters {
  string defaultValue: 'rICHARD', name: 'lAST'
}

environment{
  NAME= "NIKHIL"
}


tools {
  maven 'maven_test'
}

stages{

    stage ('build')
    {
        steps{
          script {
              dir('maven-project-master/') {
                sh 'mvn clean package'
                echo "echo $NAME ${PARAMS.lAST}"
        }
        }
        }
        post {
        success {
            archiveArtifacts artifacts: '**/target/*.war'
                }
            }
    }

}
}
