pipeline
{
agent {
  label 'dev'
}

parameters {
  string defaultValue: 'Richard', name: 'LAST'
}

environment{
  NAME = "NIKHIL"
}

tools {
  maven 'maven_test'
}

stages{

    stage ('build')
    {
        steps{
          script {
              dir('maven-project-master/') {
                sh 'mvn clean package'
                echo "hello $NAME ${params.LAST}"
        }
        }
        }
        post {
        success {
            archiveArtifacts artifacts: '**/target/*.war'
                }
            }
    }

}
}
